### ISSUE TITLE
Typing ".*" in crashes the demo

### ISSUE THREAD

**Issue by sankarravi** [bvaughn/react-highlight-words#12]
In general, it's pretty surprising that input is interpreted as a regex by default, so that "." highlights all characters. But it seems particularly bad that ".*" crashes the highlighter unless you specifically turn on `autoEscape`. This is reproducible at https://bvaughn.github.io/react-highlight-words/

I would consider defaulting `autoEscape` on, but I don't want to overprescribe a solution to the bug.

**Comment by bvaughn** [comment]
Input is interpreted as a regex because changing the default would require a major release. (It's also pretty simple for application code to pre-filter if they don't want regex behavior.)

I agree that the crashing behavior you describe is pretty awful though. I'll try to look into it sometime soon.

**Comment by EnixCoda** [comment]
`\b` crashes demo too

**Comment by lyubomyr-rudko** [comment]
`$` letter crashes the demo and component crashes

**Comment by bvaughn** [comment]
Feel free to contribute a fix if you have any ideas.

Unfortunately I don't have the time to look into this.
