### ISSUE TITLE
Should accept regular expression as element in searchWords array

### ISSUE THREAD

**Issue by rayshan** [bvaughn/react-highlight-words#29]
Hi, thanks so much for this library. I try to pass `[new RegExp(`\\b(${myVariable})\\b`, 'i')]` to `searchWords`. It works fine but produces below warning:

```
Warning: Failed prop type: Invalid prop `searchWords[0]` of type `regexp` supplied to `Highlighter`, expected `string`.
```

**Comment by bvaughn** [comment]
This isn't how the library works. 😄 You pass it an array of strings and [it converts them to regular expressions](https://github.com/bvaughn/highlight-words-core/blob/003b1511847544f8aa222e06cd9ef9165702ffd0/src/utils.js#L77).

If you feel the component should work differently, I'd be happy to review a PR. 😁 Otherwise I think it's fine as-is.
