### ISSUE TITLE
Case-insensitivity only works if the searchword string is 1 character long

### ISSUE THREAD

**Issue by nicholasengleman** [bvaughn/react-highlight-words#49]
I'm having problems with the case-sensitivity. 

It seems like the case-insensitivity only works if the searchword string is 1 character long.

For example, if I am highlighting text in the string "Prom", and my searchword string is "p", it works as expected, finds the "P" and highlights. But if the searchword string is "pr", it doesn locate the "Pr" in my original string.

Similarly, if I am highlighting text in the string "FRench", and my searchword string is "f", it find the "F" and highlights. But if the searchword string is "fr", it doesn locate the "FR" in my original string. 

One last example with same string("FRench"): if my searchword string is "r", it find the "R". But if the searchword string is "re", it doesn locate the "Re" in my original string.

**Comment by bvaughn** [comment]
The [Code Sandbox demo](https://codesandbox.io/s/5v8yqoxv7k) that's linked to from the home page does not repro the behavior you're describing. (The search term "the" highlights "The" and "the".)

I'll need you to provide a repro case (preferably using Code Sandbox) that shows this behavior. Otherwise, it seems to be working fine.
