### ISSUE TITLE
Unwanted bold style

### ISSUE THREAD

**Issue by Neraste** [bvaughn/react-highlight-words#5]
Hi there, thank you for this component.

When using it, I was surprised to get a bold style for each highlighted piece of string. This bold style is due to the `Highlighter.css` `Term` class, transmitted by a class of random generated name. I don't need it and the only way to get rid off this default style is to pass an `highlightStyle` attribute for each call of the component, or to set a counter style with `!important` in my CSS, which is in either case not convenient.

**Comment by bvaughn** [comment]
Hi @Neraste,

You're welcome! :)

If you don't like passing a `highlightStyle` you should also be able to override the bold style by passing a `highlightClassName` that sets `font-weight: normal`. I understand that this requires a little effort but I don't think it's an unreasonable amount.

That being said... since I'm using a `<mark>` element and the browser specifies default (if ugly) styling for it... I guess I don't _need_ to specify any style at all.

Let me think on it for a few. :)

**Comment by bvaughn** [comment]
I think your request is reasonable. Version 0.1.7 just released. No more default bold style.

**Comment by Neraste** [comment]
I think you don't need to specify any. Especially because you provide a `highlightClassName` attribute and this way, you separate the content from the style.

What is also misleading, is that all your examples are not bold.

**Comment by Neraste** [comment]
Oh, nice!
